name: Check and Update Image

on:
  schedule:
    - cron: '0 4 */4 * *'
  workflow_dispatch:

jobs:
  imageBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get speedscope release version 
        id: speedscope
        shell: bash {0}
        run: |
          release_tag=$(curl -s https://api.github.com/repos/jlfwong/speedscope/releases/latest | jq -r '.tag_name')
          echo "release_tag=$release_tag" >> $GITHUB_OUTPUT
          current_tag=$([ -f VERSION_TAG ] && cat VERSION_TAG)
          echo "current_tag=$current_tag" >> $GITHUB_OUTPUT
      - name: Install bsdtar
        run: |
          sudo apt-get update
          sudo apt-get -y install libarchive-tools
      - name: Get speedscope latest release
        if: steps.speedscope.outputs.release_tag != steps.speedscope.outputs.current_tag
        run: |
          curl -sL $(curl -s https://api.github.com/repos/jlfwong/speedscope/releases/latest | jq -r '.assets[].browser_download_url') | bsdtar -xf -
      - name: Set up QEMU
        if: steps.speedscope.outputs.release_tag != steps.speedscope.outputs.current_tag
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        if: steps.speedscope.outputs.release_tag != steps.speedscope.outputs.current_tag
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: steps.speedscope.outputs.release_tag != steps.speedscope.outputs.current_tag
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: steps.speedscope.outputs.release_tag != steps.speedscope.outputs.current_tag
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            mortum5/speedscope:${{ steps.speedscope.outputs.release_tag }}
            mortum5/speedscope:latest
      - name: Docker Hub Update Description
        if: steps.speedscope.outputs.release_tag != steps.speedscope.outputs.current_tag
        uses: peter-evans/dockerhub-description@v4
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            repository: mortum5/speedscope
      - name: Commit new version
        if: steps.speedscope.outputs.release_tag != steps.speedscope.outputs.current_tag
        run: |
          echo ${{ steps.speedscope.outputs.release_tag }} > VERSION_TAG
          git config --global user.name 'CI'
          git config --global user.email 'ci@noreply.com'
          git add VERSION_TAG
          git commit -m "ci: update version tag to ${{ steps.speedscope.outputs.release_tag }}"
          git push
